# Generated by Django 5.1.7 on 2025-03-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Black_Friday_data_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(default=0)),
                ('Product_ID', models.CharField(default='', max_length=10)),
                ('Purchase', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Black_Friday_data_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(default=0)),
                ('Product_ID', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('Age', models.CharField(default=0, max_length=10)),
                ('Occupation', models.IntegerField(default=0)),
                ('City_Category', models.TextField(default='', max_length=10)),
                ('Stay_In_Current_City_Year', models.IntegerField(default=0)),
                ('Marital_Status', models.IntegerField(default=0)),
                ('Product_Category_1', models.IntegerField(default=0)),
                ('Product_Category_2', models.IntegerField(default=0)),
                ('Product_Category_3', models.IntegerField(default=0)),
                ('Purchase', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Black_Friday_data_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(default=0)),
                ('Product_ID', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('Age', models.CharField(default=0, max_length=10)),
                ('Occupation', models.IntegerField(default=0)),
                ('City_Category', models.TextField(default='', max_length=10)),
                ('Stay_In_Current_City_Year', models.CharField(default=0, max_length=10)),
                ('Marital_Status', models.CharField(default=0, max_length=10)),
                ('Product_Category_1', models.IntegerField(default=0)),
                ('Product_Category_2', models.IntegerField(default=0)),
                ('Product_Category_3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Boston_Data_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRIM', models.FloatField(default=0)),
                ('ZN', models.FloatField(default=0)),
                ('INDUS', models.FloatField(default=0)),
                ('CHAS', models.FloatField(default=0)),
                ('NOX', models.FloatField(default=0)),
                ('RM', models.FloatField(default=0)),
                ('AGE', models.FloatField(default=0)),
                ('DIS', models.FloatField(default=0)),
                ('RAD', models.IntegerField(default=0)),
                ('TAX', models.IntegerField(default=0)),
                ('PTRATIO', models.FloatField(default=0)),
                ('B', models.FloatField(default=0)),
                ('LSTAT', models.FloatField(default=0)),
                ('PRICE', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Red_Wine_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fixed_Acidity', models.FloatField(default=0)),
                ('volatile_Acidity', models.FloatField(default=0)),
                ('Citric_Acid', models.FloatField(default=0)),
                ('Residual_Sugar', models.FloatField(default=0)),
                ('Chlorides', models.FloatField(default=0)),
                ('Free_Sulfur_Dioxide', models.IntegerField(default=0)),
                ('Total_Sulfur_Dioxide', models.IntegerField(default=0)),
                ('Density', models.FloatField(default=0)),
                ('Ph', models.FloatField(default=0)),
                ('Sulphates', models.FloatField(default=0)),
                ('Alcohol', models.FloatField(default=0)),
                ('Quality', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Walmart_data_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store', models.IntegerField(default=0)),
                ('Date', models.DateField(default='')),
                ('Temperature', models.FloatField(default=0)),
                ('Fuel_Price', models.FloatField(default='')),
                ('MarkDown1', models.FloatField(default=0)),
                ('MarkDown2', models.FloatField(default=0)),
                ('MarkDown3', models.FloatField(default=0)),
                ('MarkDown4', models.FloatField(default=0)),
                ('MarkDown5', models.FloatField(default=0)),
                ('CPI', models.FloatField(default=0)),
                ('Unemployment', models.FloatField(default=0, max_length=10)),
                ('IsHoliday', models.BooleanField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Walmart_data_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store', models.IntegerField(default=0)),
                ('Type', models.CharField(default='', max_length=10)),
                ('Size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Walmart_data_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store', models.IntegerField(default=0)),
                ('Dept', models.IntegerField(default=0)),
                ('Date', models.DateField(default='')),
                ('Weekly_Sales', models.FloatField()),
                ('IsHoliday', models.BooleanField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Walmart_data_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store', models.IntegerField(default=0)),
                ('Dept', models.IntegerField(default=0)),
                ('Date', models.DateField(default='')),
                ('IsHoliday', models.BooleanField(default='')),
            ],
        ),
    ]
